# -*- coding: utf-8 -*-
"""T5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12l6UdRsGwU7-CxRJVA4Wvj_M1VYQWJ3t
"""

# ===== INSTALL REQUIRED LIBRARIES =====
!pip install pandas openpyxl scikit-learn ftfy
!pip install transformers datasets sentencepiece evaluate accelerate pandas


# ===== IMPORT =====
import pandas as pd
from sklearn.model_selection import train_test_split
from ftfy import fix_text
import pandas as pd
from transformers import T5Tokenizer, T5ForConditionalGeneration,TrainingArguments, Trainer
import evaluate
import torch


# ===== LOAD DATASET =====
df = pd.read_excel("dataset.xlsx")

df.columns = ["tweet","english"]

# ===== FIX ENCODING ISSUES =====
df["tweet"] = df["tweet"].astype(str).apply(fix_text)
df["english"] = df["english"].astype(str).apply(fix_text)

df = df.dropna()

df.to_csv("dataset_clean.csv", index=False)

# ===== SPLIT TRAIN / TEST =====
train, test = train_test_split(df, test_size=0.13, random_state=42)

train.to_csv("train.csv", index=False)
test.to_csv("test.csv", index=False)

# ===== INFO =====
print("Total samples:", len(df))
print("Train samples:", len(train))
print("Test samples:", len(test))
print("Files created: dataset_clean.csv, train.csv, test.csv")

# ================= LOAD DATA =================


train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

train_df.columns = ["tweet","english"]
test_df.columns = ["tweet","english"]

# FORCE STRING TYPE
train_df["tweet"] = train_df["tweet"].astype(str)
train_df["english"] = train_df["english"].astype(str)

test_df["tweet"] = test_df["tweet"].astype(str)
test_df["english"] = test_df["english"].astype(str)

# ADD PREFIX
train_df["input_text"] = "translate romanized telugu to english: " + train_df["tweet"]
test_df["input_text"] = "translate romanized telugu to english: " + test_df["tweet"]

train_df["target_text"] = train_df["english"]
test_df["target_text"] = test_df["english"]

train_dataset = Dataset.from_pandas(train_df[["input_text","target_text"]])
test_dataset = Dataset.from_pandas(test_df[["input_text","target_text"]])

# ================= LOAD MODEL =================
model_name = "t5-small"

tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

print("GPU:", torch.cuda.get_device_name(0))

# ================= TOKENIZATION =================

def tokenize(batch):

    inputs = tokenizer(
        batch["input_text"],
        padding="max_length",
        truncation=True,
        max_length=64
    )

    targets = tokenizer(
        batch["target_text"],
        padding="max_length",
        truncation=True,
        max_length=64
    )

    inputs["labels"] = targets["input_ids"]
    return inputs


train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)


# ================= DATA COLLATOR =================
from transformers import DataCollatorForSeq2Seq
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)


# ================= TRAINING SETTINGS =================
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=1e-4,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=6,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=20,
    weight_decay=0.01
)


# ================= TRAINER =================
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
)


# ================= TRAIN MODEL =================
trainer.train()


# ================= SAVE MODEL =================
model.save_pretrained("telugu_romanized_translator")
tokenizer.save_pretrained("telugu_romanized_translator")

trainer.evaluate()

tests = [
"movie bagundi kani climax slow",
"naku ee song chala nachindi",
"ee cafe ambience chala stylish ga undi",
"memu frnds tho movie ki vellam",
"match chala interesting ga undi",
"exam ela rasav ra",
"emina tintava order pettana cook cheskundama"
]

for t in tests:
    text = "translate romanized telugu to english: " + t
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_length=50)
    print("INPUT :", t)
    print("OUTPUT:", tokenizer.decode(output[0], skip_special_tokens=True))
    print()

!zip -r model.zip telugu_romanized_translator

from collections import Counter

all_words = []

for t in df["tweet"]:
    all_words.extend(str(t).lower().split())

freq = Counter(all_words)

print("Vocabulary size:", len(freq))
print("Top 20 words:", freq.most_common(20))

rare = sum(1 for w,c in freq.items() if c == 1)
print("Rare word ratio:", rare/len(freq))

bleu = evaluate.load("bleu")

predictions = []
references = []

for row in test_df.itertuples():

    text = "translate romanized telugu to english: " + str(row.tweet)

    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    output = model.generate(
        **inputs,
        max_length=60,
        num_beams=5,
        early_stopping=True
    )

    pred = tokenizer.decode(output[0], skip_special_tokens=True)

    predictions.append(pred)
    references.append([str(row.english)])

score = bleu.compute(predictions=predictions, references=references)

print("BLEU score:", score["bleu"])

